### ISSUE TITLE
Integration Tests for Minecraft with SpecFlow code?

### ISSUE THREAD

**Issue by rogermiranda1000** [SpecFlowOSS/Streaming-Projects#1]
Where can I find the ["Write Integration Tests for Minecraft with SpecFlow and Mineflayer" project](https://youtu.be/_CTUBrnNW5U) code, by @SabotageAndi (stream recorded on 2021-02-04)?

**Comment by SabotageAndi** [comment]
For some reason, it is in a private repo. Let me check why it is private and I will get back to you.

**Comment by SabotageAndi** [comment]
@rogermiranda1000 Repo is public at https://github.com/SabotageAndi/AutomateMinecraftWithSpecFlow
